securities:
  - name: "MSCI World ETF"
    identifier: "URTH"
    mu: 0.09
    sigma: 0.14
    type: "equity"

  - name: "NASDAQ-100 ETF"
    identifier: "QQQ"
    mu: 0.12
    sigma: 0.20
    type: "equity"

  - name: "Nasdaq 100 ETF 2x Leveraged"
    identifier: "QLD"
    base: "QQQ"
    leverage: 2
    type: "leveraged"

portfolio:
  name: "CS1"
  value: 100000
  weights: [0.85, 0, 0.15]

rebalancing: true
